name: Build and Push Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Find changed directories
        id: changed-dirs
        run: |
          # First, check if the HEAD is a valid commit
          if git rev-parse --verify HEAD^ > /dev/null 2>&1; then
            # If it is, list the changed directories
            changed_dirs=$(git diff --name-only HEAD^ HEAD | xargs -I {} dirname {} | sort | uniq)
          else
            # Otherwise, list all directories
            changed_dirs=$(git ls-tree --full-tree --name-only -r HEAD | xargs -I {} dirname {} | sort | uniq)
          fi

          echo "Changed directories: $changed_dirs"
          # Save the changed directories to an output variable
          echo "dirs=$changed_dirs" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        run: |
          for dir in ${{ steps.changed-dirs.outputs.dirs }}; do
            if [ -f "$dir/Dockerfile" ]; then
              image_name="${{ secrets.DOCKER_HUB_USERNAME }}/$(basename $dir)"
              echo "Building and pushing $image_name from $dir"
              docker build --progress=plain -t $image_name $dir
              docker push $image_name
            fi
          done